version: "3"
volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: Ch1ckenF00t
  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: Ch1ckenF00t
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Ch1ckenF00t
    ports:
      - "8080:8080"
    depends_on:
      - postgres
